export const LOADCHATHISTORY_LOAD = 'CHATBOT/LOADCHATHISTORY_LOAD';
export const SEND_ASK = 'CHATBOT/SEND_ASK';
export const LOADCHATHISTORY_CHAT_ADDED = 'CHATBOT/LOADCHATHISTORY_CHAT_ADDED';
export const LOADCHATHISTORY_FLOW_OPEN = 'CHATBOT/LOADCHATHISTORY_FLOW_OPEN';
export const LOADCHATHISTORY_FLOW_END = 'CHATBOT/LOADCHATHISTORY_FLOW_END';
export const LOADCHATHISTORY_SENDING = 'CHATBOT/LOADCHATHISTORY_SENDING';
export const LOADCHATHISTORY_SENDING_END = 'CHATBOT/LOADCHATHISTORY_SENDING_END';
